### ISSUE TITLE
using variable called "arguments" makes strict mode fail

### ISSUE THREAD

**Issue by simon-lang** [userapp-io/userapp-javascript#4]
In JS "arguments" is a reserved word (kind of) that refers to the current function's arguments. Like argv.

If you have a 'use strict' at the top of your file, you'll get this error:

```
Uncaught SyntaxError: Unexpected eval or arguments in strict mode
```

I noticed this because I was combining this file and the [userapp angular module](https://github.com/userapp-io/userapp-angular/blob/master/angularjs.userapp.js) with uglify. Since they have their 'use strict' declaration outside of their closure it gets hoisted to the top and breaks this module.

Anyway, it is easily fixed by renaming every usage of "arguments" in your codebase to "args". Worked fine for me locally.

**Comment by yucheng-xu** [comment]
Thanks, was looking for solving this exact problem for 5 minutes.

**Comment by simon-lang** [comment]
not fixed, just clearing out my open issues list
